org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
org.gradle.caching=true
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
ksp.useKSP2=false
# YouTube Data API v3 key (default, app mein pehle se lagi aati hai). Repo PRIVATE rakho.
sangeet.youtubeApiKey=AIzaSyB1kFxcI23xi418PgROIaGhT_-p2DG33Pw
